<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class PhotoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $photos = [
            [
                'user_id' => 1,
                'spot_id' => 2,
                'storage_path' => 'photos/demo/photo_1.jpg',
                'thumbnail_path' => 'photos/demo/thumb_1.jpg',
                'original_filename' => 'geku_torii.jpg',
                'mime_type' => 'image/jpeg',
                'file_size' => 2048000,
                'caption' => '外宮の鳥居。朝の光が差し込んで神々しい雰囲気。',
                'taken_at' => '2026-03-28 09:35:00',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 2,
                'spot_id' => 2,
                'storage_path' => 'photos/demo/photo_2.jpg',
                'thumbnail_path' => 'photos/demo/thumb_2.jpg',
                'original_filename' => 'geku_sando.jpg',
                'mime_type' => 'image/jpeg',
                'file_size' => 1856000,
                'caption' => '外宮の参道。砂利道が気持ちいい。',
                'taken_at' => '2026-03-28 09:50:00',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 1,
                'spot_id' => 1,
                'storage_path' => 'photos/demo/photo_3.jpg',
                'thumbnail_path' => 'photos/demo/thumb_3.jpg',
                'original_filename' => 'naiku_ujibashi.jpg',
                'mime_type' => 'image/jpeg',
                'file_size' => 3200000,
                'caption' => '宇治橋からの眺め。五十鈴川の水が澄んでいてきれい！',
                'taken_at' => '2026-03-28 11:05:00',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 2,
                'spot_id' => 1,
                'storage_path' => 'photos/demo/photo_4.jpg',
                'thumbnail_path' => 'photos/demo/thumb_4.jpg',
                'original_filename' => 'naiku_shogu.jpg',
                'mime_type' => 'image/jpeg',
                'file_size' => 2560000,
                'caption' => '内宮正宮の石段。厳かな空気が漂っている。',
                'taken_at' => '2026-03-28 11:45:00',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 1,
                'spot_id' => 3,
                'storage_path' => 'photos/demo/photo_5.jpg',
                'thumbnail_path' => 'photos/demo/thumb_5.jpg',
                'original_filename' => 'akafuku.jpg',
                'mime_type' => 'image/jpeg',
                'file_size' => 1500000,
                'caption' => '赤福本店のできたて赤福餅。やっぱりここで食べるのが一番！',
                'taken_at' => '2026-03-28 12:40:00',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 2,
                'spot_id' => 3,
                'storage_path' => 'photos/demo/photo_6.jpg',
                'thumbnail_path' => 'photos/demo/thumb_6.jpg',
                'original_filename' => 'ise_udon.jpg',
                'mime_type' => 'image/jpeg',
                'file_size' => 1750000,
                'caption' => '伊勢うどん！太くてもちもちで美味しかった。',
                'taken_at' => '2026-03-28 13:10:00',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 1,
                'spot_id' => 3,
                'storage_path' => 'photos/demo/photo_7.jpg',
                'thumbnail_path' => 'photos/demo/thumb_7.jpg',
                'original_filename' => 'okage_street.jpg',
                'mime_type' => 'image/jpeg',
                'file_size' => 2100000,
                'caption' => 'おかげ横丁の街並み。江戸時代にタイムスリップしたみたい。',
                'taken_at' => '2026-03-28 13:45:00',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 2,
                'spot_id' => 5,
                'storage_path' => 'photos/demo/photo_8.jpg',
                'thumbnail_path' => 'photos/demo/thumb_8.jpg',
                'original_filename' => 'meoto_iwa.jpg',
                'mime_type' => 'image/jpeg',
                'file_size' => 2800000,
                'caption' => '夫婦岩。注連縄で結ばれた2つの岩が素敵。',
                'taken_at' => '2026-03-28 15:20:00',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 1,
                'spot_id' => 5,
                'storage_path' => 'photos/demo/photo_9.jpg',
                'thumbnail_path' => 'photos/demo/thumb_9.jpg',
                'original_filename' => 'futami_kaigan.jpg',
                'mime_type' => 'image/jpeg',
                'file_size' => 2400000,
                'caption' => '二見浦の海岸線。波の音が心地よかった。',
                'taken_at' => '2026-03-28 15:40:00',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 2,
                'spot_id' => 7,
                'storage_path' => 'photos/demo/photo_10.jpg',
                'thumbnail_path' => 'photos/demo/thumb_10.jpg',
                'original_filename' => 'asamayama_view.jpg',
                'mime_type' => 'image/jpeg',
                'file_size' => 3500000,
                'caption' => '朝熊山展望台からの絶景！伊勢湾が一望できる。',
                'taken_at' => '2026-03-29 09:15:00',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 1,
                'spot_id' => 7,
                'storage_path' => 'photos/demo/photo_11.jpg',
                'thumbnail_path' => 'photos/demo/thumb_11.jpg',
                'original_filename' => 'kongoshoji.jpg',
                'mime_type' => 'image/jpeg',
                'file_size' => 2200000,
                'caption' => '金剛證寺の本堂。歴史を感じる佇まい。',
                'taken_at' => '2026-03-29 09:50:00',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 2,
                'spot_id' => 6,
                'storage_path' => 'photos/demo/photo_12.jpg',
                'thumbnail_path' => 'photos/demo/thumb_12.jpg',
                'original_filename' => 'amanoiwato.jpg',
                'mime_type' => 'image/jpeg',
                'file_size' => 1900000,
                'caption' => '天の岩戸の湧き水。透き通っていて神秘的。',
                'taken_at' => '2026-03-29 11:20:00',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 1,
                'spot_id' => 4,
                'storage_path' => 'photos/demo/photo_13.jpg',
                'thumbnail_path' => 'photos/demo/thumb_13.jpg',
                'original_filename' => 'vison_marche.jpg',
                'mime_type' => 'image/jpeg',
                'file_size' => 2650000,
                'caption' => 'VISONのマルシェ。地元の食材がたくさん並んでいる。',
                'taken_at' => '2026-03-29 13:00:00',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 2,
                'spot_id' => null,
                'storage_path' => 'photos/demo/photo_14.jpg',
                'thumbnail_path' => 'photos/demo/thumb_14.jpg',
                'original_filename' => 'two_shot.jpg',
                'mime_type' => 'image/jpeg',
                'file_size' => 1800000,
                'caption' => '旅行中のツーショット。楽しい2日間だった！',
                'taken_at' => '2026-03-29 14:30:00',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('photos')->insert($photos);
    }
}
